-- Migration 014: Seed keyword triggers for comment-to-DM workflow
INSERT INTO keyword_triggers (keyword, dm_template_en, dm_template_es, program_slug) VALUES
('PODS', E'Hey there! \U0001F44B I''m Maribel from Eaton Academic. Thanks for your interest in our Learning Pods!\n\nOur pods are small-group, in-person classes here in South Florida with amazing teachers. I''d love to help you find the right fit \u2014 what grade is your child in?', E'\u00A1Hola! \U0001F44B Soy Maribel de Eaton Academic. \u00A1Gracias por tu inter\u00E9s en nuestros Learning Pods!\n\nNuestros pods son clases presenciales en grupos peque\u00F1os aqu\u00ED en el sur de la Florida con excelentes maestros. Me encantar\u00EDa ayudarte a encontrar la opci\u00F3n ideal \u2014 \u00BFen qu\u00E9 grado est\u00E1 tu hijo/a?', 'pods'),

('SCHEDULE', E'Hi! \U0001F44B I''m Maribel from Eaton Academic. I''d be happy to share our class schedule with you!\n\nAre you looking for in-person classes in South Florida, or our online classes that are available nationwide?', E'\u00A1Hola! \U0001F44B Soy Maribel de Eaton Academic. \u00A1Con gusto te comparto nuestro horario de clases!\n\n\u00BFBuscas clases presenciales en el sur de la Florida, o nuestras clases en l\u00EDnea disponibles en todo el pa\u00EDs?', 'general'),

('INFO', E'Hey! \U0001F44B I''m Maribel from Eaton Academic. Thanks for reaching out!\n\nWe offer learning pods, online classes, academic coaching, and more for homeschool families. What would you like to know more about?', E'\u00A1Hola! \U0001F44B Soy Maribel de Eaton Academic. \u00A1Gracias por escribirnos!\n\nOfrecemos pods de aprendizaje, clases en l\u00EDnea, coaching acad\u00E9mico y m\u00E1s para familias que educan en casa. \u00BFQu\u00E9 te gustar\u00EDa saber?', 'general'),

('TOUR', E'Hi there! \U0001F44B I''m Maribel from Eaton Academic. We''d love to show you around!\n\nI can help set up a quick 15-minute call with our team to go over programs and answer any questions. Would you like me to find some available times?', E'\u00A1Hola! \U0001F44B Soy Maribel de Eaton Academic. \u00A1Nos encantar\u00EDa mostrarte nuestras instalaciones!\n\nPuedo ayudarte a coordinar una llamada r\u00E1pida de 15 minutos con nuestro equipo. \u00BFTe gustar\u00EDa que busque horarios disponibles?', 'microschool'),

('EVENT', E'Hey! \U0001F44B I''m Maribel from Eaton Academic. Thanks for your interest in our events!\n\nLet me share what we have coming up. What age group is your child in?', E'\u00A1Hola! \U0001F44B Soy Maribel de Eaton Academic. \u00A1Gracias por tu inter\u00E9s en nuestros eventos!\n\nPerm\u00EDteme compartirte lo que tenemos pr\u00F3ximamente. \u00BFEn qu\u00E9 grupo de edad est\u00E1 tu hijo/a?', 'events'),

('WAITLIST', E'Hi! \U0001F44B I''m Maribel from Eaton Academic. Great timing \u2014 you can join our waitlist right here:\n\nhttps://eatonacademic.app.n8n.cloud/form/f7e68662-d872-4da0-91b9-a8b239b839fb\n\nWhich program are you most interested in? I can give you more details while you wait!', E'\u00A1Hola! \U0001F44B Soy Maribel de Eaton Academic. \u00A1Qu\u00E9 bueno que escribes! Puedes unirte a nuestra lista de espera aqu\u00ED:\n\nhttps://eatonacademic.app.n8n.cloud/form/f7e68662-d872-4da0-91b9-a8b239b839fb\n\n\u00BFQu\u00E9 programa te interesa m\u00E1s? \u00A1Puedo darte m\u00E1s detalles mientras esperas!', 'general');
